
# Site Settings

title: Show me What you Got  # Your Title 
subtitle: Tech, Data, Game-Nerd
email: samueltseng@icloud.com  # Your Email
description: >-  
  Personal blog with brief CV, working notes and life sharing.
baseurl:  # the subpath of your site, e.g. /blog
url: "https://samuelTyh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: samuelTyh
github_username:  samuelTyh
google_analytics: "UA-158696220-1"

# Navigation 

urls:
    - text: About
      url: /
    - text: Blog
      url: /blog
    # - text: Shop
      # url : /shop
    # - text: Sample Page
      # url: /sample-page
    - text: Contact Me
      url : /contact

# Author Details

author_logo: profile.jpg
author: Samuel Tseng
author_bio: Samuel Tseng. Data/Tech enthusiast based in Berlin, Germany. 
  I have more than 7 years of experience in different realms, including education, banking/leasing, consultant, retail, IT service industries.
  I also come with 3 years in the data science profession.
  Mainly focus on implementing data science projects and product prototyping.
author_email: "samueltseng@icloud.com"
author_location: Berlin, Germany
author_website_url: "https://samuelTyh.github.io"

# social links
twitter_username: samuelTyh
github_username:  samuelTyh
facebook_username: SamInDeutschland
linkedin_username: samuel-tseng

# Choose what to show ( true - display or false - don't display)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

author_work_experiences: 
            - company_name: digitty.io GmbH
              company_logo: digittyio.png
              company_url: https://digitty.io
              designation: Data Scientist (Feb 2019 - Apr 2020)
              description: Worked on digitty.io AI platform and Intelligence solution for costomer and business strategy. 
                Mainly focus on implementing data science projects and product prototyping.
              visibility: true
            - company_name: Samuel.Tseng
              company_logo: selfemployed.jpg
              company_url: 
              designation: Freelance Data Science Engineer (Aug 2017 - PRESENT)
              description: Worked on several projects for corporations in Berlin and Taipei. 
                The latest project was to serve as a Data Science contributor/consultant at Covid-data.info.
              visibility: true

author_education_details:
              - college_logo: nuk.jpg
                college_name: National University of Kaohsiung
                college_url: https://www.nuk.edu.tw/?Lang=en
                college_degree: B.Sc, Applied Mathematics
                description: Major in Applied Mathematics, solid trained in mathematical, statistical thinking, hands-on experience of Matlab and R language.
                visibility: true

author_project_details:
              - project_thumbnail: team-logo.png
                project_title: Ist Alles in Ordnung?
                project_description: A Google Dialogflow application integrated with Python/Flask and Twitter API
                project_url: https://github.com/pymia/ist-alles-in-ordnung
                visibility: true
              - project_thumbnail: cvparser.jpeg
                project_title: CV parser
                project_description: Implemented customized Name Entity Recognition (NER) by spaCy. Recreated 11 classes of name entities, trained the model, wrapped into API and deployed to the cloud.
                project_url: https://github.com/samuelTyh/cv-parser-via-customized-ner
                visibility: true
                
#for comments using disqus
disqus_shortname: samuelTyh

# wakatime username
wakatime_username: samuelTyh

# formspree username
formspree_email: mdogzkag

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# pagination of posts
paginate: 4
per_page: 5
paginate_path: "/blog/page/:num/"

# Search ( add algolia credentials below )
algolia:
  application_id: PJFAQ6B94F # add your algolia app id
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: [] 
  nodes_to_index: 'article' 
  search_only_api_key: 8ad7cc482f55d745a0a51493b3271f19 # add algolia search only api key 


# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['production']

# Shop 

collections:
 - products

# Build settings

theme: devlopr
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build